### PR TITLE
Regex

### PR DESCRIPTION
**Pull request by jidicula**
Regex cleanup to improve readability and speed.

### CODE REVIEW

**Comment by Adoria** [comment]
That regex matches to 3-digit code twice ie. `MATH 323 133`. `fac` should store the faculty code, and `num` should store the actual course number.

**Comment by jidicula** [comment]
Should be good now

**Comment by Adoria** [comment]
There should be brackets around `fac` and `num`, so we can retrieve them with `group()` later.

**Comment by jidicula** [comment]
Ok

**Pull request merged**
